# Generated by Django 6.0.5 on 2026-06-10 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Legenda')),
                ('imagem', models.ImageField(upload_to='timeline/', verbose_name='Imagem')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Timeline',
                'verbose_name_plural': 'Itens de Timeline',
                'ordering': ['-data'],
            },
        ),
    ]
